services:
  app:
    image: hello-front-dev
    build:
      context: . 
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/todo-frontend
    ports:
      - 3001:3000
    container_name: todo-front